version: '3.9'

services:

  test_1:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - '.env'
    volumes:
      - ${LOCAL_CREDENTIALS}:${CONTAINER_CREDENTIALS}
      - ./tests/test_1:/tests/test_1
      - ./allure-results:/allure-results
      - ./allure-reports:/allure-reports
    command: >
      bash -c "pytest -n ${PARALLEL} --alluredir=allure-results"
    restart: on-failure

  allure-server:
    image: frankescobar/allure-docker-service:latest
    volumes:
      - ./allure-results:/allure-results
      - ./allure-reports:/allure-reports
    ports:
      - ${ALLURE_PORT}
    healthcheck:
      test: ["CMD-SHELL", "python --version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 2
    deploy:
      resources:
        limits:
          cpus: '2'
    restart: on-failure
    depends_on:
      test_1:
        condition: service_completed_successfully
    command: >
       bash -c "allure generate /allure-results --clean -o /allure-reports && allure serve"

volumes:
  shared:
